spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/schema_name
      username: root
      password: ld8221266
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/schema_name1
      username: root
      password: ld8221266